/**
 * Sample playback for the 1970s arsenal (public/audio/weapons/<id>/<name>.wav, generated by
 * tools/weapon-1970s/make_sounds.py). Samples load lazily per weapon, so the casino starts as
 * fast as before; the first shot of a freshly awarded gun may fall back to silence while its
 * few hundred kilobytes arrive. The caller uses synthesized fallback voices until samples
 * are ready; the Mystery Box also preloads its reward during the spin.
 */
import type { GameEvent, V2, WeaponId } from "./simulation";
import { VIEWMODELS } from "./weapon-viewmodels.ts";

export const WEAPON_SOUNDS: Partial<Record<WeaponId, string[]>> = {
  magnum: ["fire", "dry", "reload-start", "eject", "reload-loop", "reload-end", "pickup"],
  tommy: ["fire-1", "fire-2", "fire-3", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  doublebarrel: ["fire", "fire-alt", "dry", "reload-start", "eject", "reload-loop", "reload-end", "cock", "pickup"],
  dual: ["fire-right-1", "fire-right-2", "fire-left-1", "fire-left-2", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  machinepistol: ["fire-1", "fire-2", "fire-3", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  lever: ["fire", "cycle", "cycle-close", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  autoshotgun: ["fire", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  sniper: ["fire", "bolt-open", "bolt-close", "dry", "reload-start", "reload-loop", "reload-end", "pickup"],
  lmg: ["fire-1", "fire-2", "fire-3", "belt-end", "dry", "reload-start", "eject", "reload-loop", "cover", "reload-end", "pickup"],
  launcher: ["fire", "flight", "explode", "dry", "reload-start", "hinge", "eject", "reload-loop", "reload-end", "pickup"],
  stick: ["swing", "impact-1", "impact-2", "impact-3", "break", "pickup"],
  axe: ["swing", "impact-1", "impact-2", "pickup"],
};
/** Per-weapon mix: reports are normalised to the same peak, so balance them here. */
const GAIN: Partial<Record<WeaponId, number>> = {
  magnum: 0.95, tommy: 0.62, doublebarrel: 1, dual: 0.5, machinepistol: 0.5, lever: 0.8,
  autoshotgun: 0.85, sniper: 0.9, lmg: 0.7, launcher: 0.95, stick: 0.8, axe: 0.9,
};
const MECH = 0.55;

export type Bus = { context: AudioContext; world: AudioNode; reverb: AudioNode | null };

export class WeaponSounds {
  private buffers = new Map<string, AudioBuffer>();
  private loading = new Map<WeaponId, Promise<void>>();
  private variant = 0;
  private barrel = 0;
  private voices = new Map<AudioBufferSourceNode, () => void>();
  private abort = new AbortController();
  private retryAfter = new Map<WeaponId, number>();
  private generation = 0;
  private disposed = false;
  private active = true;
  lastPlayback = "none";
  private bus: () => Bus | null;
  constructor(bus: () => Bus | null) {
    this.bus = bus;
  }
  has(id: WeaponId) {
    return !!WEAPON_SOUNDS[id];
  }
  setActive(active: boolean) {
    this.active = active;
    if (!active) this.stop();
  }
  stop() {
    this.generation++;
    for (const [source, cleanup] of this.voices) {
      source.stop();
      cleanup();
    }
  }
  dispose() {
    this.disposed = true;
    this.stop();
    this.abort.abort();
    this.loading.clear();
    this.buffers.clear();
  }
  preload(id: WeaponId) {
    const names = WEAPON_SOUNDS[id];
    const bus = this.bus();
    if (this.disposed || !names || !bus || this.loading.has(id)) return this.loading.get(id);
    if (Date.now() < (this.retryAfter.get(id) ?? 0)) return;
    const job = Promise.all(names.filter(name => !this.buffers.has(`${id}/${name}`)).map(async (name) => {
      try {
        const response = await fetch(`/audio/weapons/${id}/${name}.wav`, { signal: this.abort.signal });
        if (!response.ok) return;
        const buffer = await bus.context.decodeAudioData(await response.arrayBuffer());
        if (!this.disposed) this.buffers.set(`${id}/${name}`, buffer);
      } catch {
        // Retry later; event() lets GameAudio provide an immediate fallback report.
      }
    })).then(() => {
      if (!this.disposed && names.some(name => !this.buffers.has(`${id}/${name}`))) {
        this.loading.delete(id);
        this.retryAfter.set(id, Date.now() + 2000);
      }
    });
    this.loading.set(id, job);
    return job;
  }
  play(id: WeaponId, name: string, opts: { gain?: number; pan?: number; rate?: number; delay?: number; reverb?: number; late?: boolean } = {}) {
    const bus = this.bus();
    const buffer = this.buffers.get(`${id}/${name}`);
    if (this.disposed || !this.active || !bus || bus.context.state !== "running") return false;
    if (!buffer) {
      // Handling sounds may arrive a moment late on a first pickup; reports never do.
      const asked = bus.context.currentTime;
      const generation = this.generation;
      void this.preload(id)?.then(() => {
        if (opts.late && generation === this.generation && bus.context.currentTime - asked < 0.5 && this.buffers.has(`${id}/${name}`)) this.play(id, name, { ...opts, late: false });
      });
      return false;
    }
    const c = bus.context;
    const src = c.createBufferSource();
    src.buffer = buffer;
    src.playbackRate.value = opts.rate ?? 1;
    const gain = c.createGain();
    gain.gain.value = (opts.gain ?? 1) * (GAIN[id] ?? 0.8);
    const pan = c.createStereoPanner();
    pan.pan.value = Math.max(-1, Math.min(1, opts.pan ?? 0));
    src.connect(gain);
    gain.connect(pan);
    pan.connect(bus.world);
    let send: GainNode | null = null;
    if (bus.reverb && (opts.reverb ?? 0.35) > 0) {
      send = c.createGain();
      send.gain.value = opts.reverb ?? 0.35;
      pan.connect(send);
      send.connect(bus.reverb);
    }
    src.start(c.currentTime + (opts.delay ?? 0));
    const cleanup = () => {
      src.disconnect();
      gain.disconnect();
      pan.disconnect();
      send?.disconnect();
      this.voices.delete(src);
    };
    src.onended = cleanup;
    this.voices.set(src, cleanup);
    this.lastPlayback = `${id}/${name}`;
    return true;
  }
  private pick(prefix: string, count: number) {
    this.variant = (this.variant + 1 + Math.floor(Math.random() * (count - 1))) % count;
    return `${prefix}-${this.variant + 1}`;
  }
  /** Returns true when the event was handled by a sampled weapon voice. */
  event(e: GameEvent, player: V2, yaw: number): boolean {
    const id = e.type === "stickBreak" ? "stick" : e.weapon;
    if (!id || !this.has(id)) return false;
    const jitter = () => 1 + (Math.random() - 0.5) * 0.05;
    if (e.type === "shot") {
      let played = false;
      if (id === "dual") {
        const side = e.side === 1 ? "left" : "right";
        played = this.play(id, this.pick(`fire-${side}`, 2), { pan: side === "left" ? -0.3 : 0.3, rate: jitter() });
      } else if (id === "doublebarrel") {
        this.barrel ^= 1;
        played = this.play(id, e.alternate ? "fire-alt" : "fire", { pan: e.alternate ? 0 : this.barrel ? 0.09 : -0.09, rate: jitter() });
      } else if (id === "tommy" || id === "machinepistol" || id === "lmg") played = this.play(id, this.pick("fire", 3), { rate: jitter() });
      else played = this.play(id, "fire", { rate: jitter() });
      if (id === "launcher") this.play(id, "flight", { delay: 0.06, gain: 0.5, reverb: 0.2 });
      return played;
    }
    if (e.type === "dry") return this.play(id, "dry", { gain: MECH });
    if (e.type === "pickup") {
      this.play(id, "pickup", { gain: MECH, delay: 0.02, late: true });
      return true;
    }
    if (e.type === "melee") return this.play(id, "swing", { gain: 0.7, rate: jitter() });
    if (e.type === "meleeHit") {
      for (let i = 0; i < Math.min(3, e.count ?? 1); i++)
        this.play(id, `impact-${1 + ((i + Math.floor(Math.random() * 3)) % (id === "axe" ? 2 : 3))}`, { delay: i * 0.028, gain: 1 - i * 0.2, rate: jitter() });
      return true;
    }
    if (e.type === "stickBreak") return this.play("stick", "break", { gain: 1 });
    if (e.type === "explosion" && e.weapon === "launcher" && e.position) {
      const d = Math.hypot(e.position.x - player.x, e.position.z - player.z);
      const pan = Math.sin(Math.atan2(e.position.x - player.x, e.position.z - player.z) - yaw);
      return this.play(id, "explode", { pan: pan * 0.7, gain: Math.max(0.25, 1 - d / 40), reverb: 0.6 });
    }
    // Reload timing is handled by the cue director below; keep the generic burst silent.
    return e.type === "reload" || e.type === "reloadDone";
  }
}

/**
 * Plays the mechanical beats of each reload/action at the same fractions the animators use
 * (weapon-viewmodels.ts), so a Quick Pour reload speeds both up together.
 */
export class WeaponCueDirector {
  private weapon: WeaponId | null = null;
  private progress = 0;
  private reloading = false;
  private sinceShot = 99;
  private lastMag = -1;
  private sounds: WeaponSounds;
  constructor(sounds: WeaponSounds) {
    this.sounds = sounds;
  }
  reset() {
    this.weapon = null;
    this.progress = 0;
    this.reloading = false;
    this.sinceShot = 99;
    this.lastMag = -1;
  }
  shot(id: WeaponId) {
    if (id === this.weapon) this.sinceShot = 0;
  }
  update(dt: number, s: { weapon: WeaponId; reloadRemaining: number; reloadDuration: number; mag: number; playing: boolean }) {
    const id = s.weapon;
    const spec = VIEWMODELS[id];
    if (id !== this.weapon) {
      this.weapon = id;
      this.progress = 0;
      this.reloading = false;
      this.sinceShot = 99;
      this.lastMag = s.mag;
      if (spec) void this.sounds.preload(id);
    }
    if (!spec || !s.playing) return;
    void this.sounds.preload(id);
    const reloading = s.reloadRemaining > 0;
    const p = reloading ? 1 - s.reloadRemaining / Math.max(1e-6, s.reloadDuration) : 0;
    const shellLoader = id === "lever" || id === "autoshotgun";
    if (reloading) {
      this.sinceShot = 99; // A reload supersedes the prior shot's delayed action cycle.
      const prev = this.reloading && p >= this.progress ? this.progress : 0;
      if (!this.reloading && shellLoader) this.sounds.play(id, "reload-start", { gain: MECH });
      for (const [at, name] of spec.reloadCues) if (prev < at && p >= at) this.sounds.play(id, name, { gain: MECH, reverb: 0.2 });
    } else if (this.reloading && shellLoader && s.mag > this.lastMag - 1) {
      this.sounds.play(id, "reload-end", { gain: MECH });
    }
    this.reloading = reloading;
    this.progress = p;
    const before = this.sinceShot;
    this.sinceShot += dt;
    for (const [at, name] of spec.shotCues ?? []) if (before < at && this.sinceShot >= at) this.sounds.play(id, name, { gain: MECH, reverb: 0.2 });
    if (id === "lmg" && s.mag === 0 && this.lastMag > 0 && !reloading) this.sounds.play(id, "belt-end", { gain: MECH, delay: 0.05 });
    this.lastMag = s.mag;
  }
}
